// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Saw-Fence

#ifndef UI_MAINCONTROLSCREEN_H
#define UI_MAINCONTROLSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainControlScreen
extern void ui_MainControlScreen_screen_init(void);
extern void ui_MainControlScreen_screen_destroy(void);
extern lv_obj_t * ui_MainControlScreen;
extern lv_obj_t * ui_MainControlsContainer;
extern lv_obj_t * ui_MeasureButton;
extern lv_obj_t * ui_MeasureButtonText;
extern lv_obj_t * ui_HomeAxisButton;
extern lv_obj_t * ui_MeasureButtonText2;
extern lv_obj_t * ui_ResetServoButton;
extern lv_obj_t * ui_MeasureButtonText3;
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_MeasureButtonText1;
extern lv_obj_t * ui_EditTargetButton;
extern lv_obj_t * ui_MeasureButtonText6;
extern lv_obj_t * ui_CurrentMeasurementLabel;
// CUSTOM VARIABLES
extern lv_obj_t * ui_MAIN_CONTROL_SCREEN;
extern lv_obj_t * ui_MainControlsContainer;
extern lv_obj_t * ui_MEASURE_BUTTON;
extern lv_obj_t * ui_HOME_AXIS_BUTTON;
extern lv_obj_t * ui_RESET_SERVO_BUTTON;
extern lv_obj_t * ui_SETTINGS_BUTTON;
extern lv_obj_t * ui_EDIT_TARGET_BUTTON;
extern lv_obj_t * ui_CURRENT_MEASUREMENT_LABEL;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

