// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Saw-Fence

#include "../ui.h"

lv_obj_t * ui_CURRENT_MEASUREMENT_LABEL;
lv_obj_t * ui_EDIT_TARGET_BUTTON;
lv_obj_t * ui_SETTINGS_BUTTON;
lv_obj_t * ui_RESET_SERVO_BUTTON;
lv_obj_t * ui_HOME_AXIS_BUTTON;
lv_obj_t * ui_MEASURE_BUTTON;
lv_obj_t * ui_MainControlsContainer;
lv_obj_t * ui_MAIN_CONTROL_SCREEN;
lv_obj_t * ui_MainControlScreen;
lv_obj_t * ui_MainControlsContainer;
lv_obj_t * ui_MeasureButton;
lv_obj_t * ui_MeasureButtonText;
lv_obj_t * ui_HomeAxisButton;
lv_obj_t * ui_MeasureButtonText2;
lv_obj_t * ui_ResetServoButton;
lv_obj_t * ui_MeasureButtonText3;
lv_obj_t * ui_SettingsButton;
lv_obj_t * ui_MeasureButtonText1;
lv_obj_t * ui_EditTargetButton;
lv_obj_t * ui_MeasureButtonText6;
lv_obj_t * ui_CurrentMeasurementLabel;

// event funtions

// build funtions

void ui_MainControlScreen_screen_init(void)
{
    ui_MainControlScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainControlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainControlsContainer = lv_obj_create(ui_MainControlScreen);
    lv_obj_remove_style_all(ui_MainControlsContainer);
    lv_obj_set_width(ui_MainControlsContainer, 800);
    lv_obj_set_height(ui_MainControlsContainer, 219);
    lv_obj_set_x(ui_MainControlsContainer, 5);
    lv_obj_set_y(ui_MainControlsContainer, 135);
    lv_obj_set_align(ui_MainControlsContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainControlsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeasureButton = lv_btn_create(ui_MainControlsContainer);
    lv_obj_set_width(ui_MeasureButton, 225);
    lv_obj_set_height(ui_MeasureButton, 200);
    lv_obj_set_x(ui_MeasureButton, 271);
    lv_obj_set_y(ui_MeasureButton, -9);
    lv_obj_set_align(ui_MeasureButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeasureButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MeasureButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MeasureButton, lv_color_hex(0x00D31C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MeasureButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MeasureButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeasureButtonText = lv_label_create(ui_MeasureButton);
    lv_obj_set_width(ui_MeasureButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureButtonText, 1);
    lv_obj_set_y(ui_MeasureButtonText, -1);
    lv_obj_set_align(ui_MeasureButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureButtonText, "Measure");
    lv_obj_set_style_text_color(ui_MeasureButtonText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MeasureButtonText, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeAxisButton = lv_btn_create(ui_MainControlsContainer);
    lv_obj_set_width(ui_HomeAxisButton, 161);
    lv_obj_set_height(ui_HomeAxisButton, 165);
    lv_obj_set_x(ui_HomeAxisButton, 59);
    lv_obj_set_y(ui_HomeAxisButton, 10);
    lv_obj_set_align(ui_HomeAxisButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeAxisButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeAxisButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeasureButtonText2 = lv_label_create(ui_HomeAxisButton);
    lv_obj_set_width(ui_MeasureButtonText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureButtonText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureButtonText2, 1);
    lv_obj_set_y(ui_MeasureButtonText2, -1);
    lv_obj_set_align(ui_MeasureButtonText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureButtonText2, "Home\n  Axis");
    lv_obj_set_style_text_font(ui_MeasureButtonText2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetServoButton = lv_btn_create(ui_MainControlsContainer);
    lv_obj_set_width(ui_ResetServoButton, 161);
    lv_obj_set_height(ui_ResetServoButton, 165);
    lv_obj_set_x(ui_ResetServoButton, -124);
    lv_obj_set_y(ui_ResetServoButton, 10);
    lv_obj_set_align(ui_ResetServoButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetServoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetServoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeasureButtonText3 = lv_label_create(ui_ResetServoButton);
    lv_obj_set_width(ui_MeasureButtonText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureButtonText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureButtonText3, 1);
    lv_obj_set_y(ui_MeasureButtonText3, -1);
    lv_obj_set_align(ui_MeasureButtonText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureButtonText3, "Reset\nServo");
    lv_obj_set_style_text_font(ui_MeasureButtonText3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButton = lv_btn_create(ui_MainControlsContainer);
    lv_obj_set_width(ui_SettingsButton, 161);
    lv_obj_set_height(ui_SettingsButton, 165);
    lv_obj_set_x(ui_SettingsButton, -306);
    lv_obj_set_y(ui_SettingsButton, 8);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeasureButtonText1 = lv_label_create(ui_SettingsButton);
    lv_obj_set_width(ui_MeasureButtonText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureButtonText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureButtonText1, 1);
    lv_obj_set_y(ui_MeasureButtonText1, -1);
    lv_obj_set_align(ui_MeasureButtonText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureButtonText1, "Settings");
    lv_obj_set_style_text_font(ui_MeasureButtonText1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EditTargetButton = lv_btn_create(ui_MainControlScreen);
    lv_obj_set_width(ui_EditTargetButton, 225);
    lv_obj_set_height(ui_EditTargetButton, 200);
    lv_obj_set_x(ui_EditTargetButton, 275);
    lv_obj_set_y(ui_EditTargetButton, -88);
    lv_obj_set_align(ui_EditTargetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EditTargetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EditTargetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EditTargetButton, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EditTargetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_EditTargetButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EditTargetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeasureButtonText6 = lv_label_create(ui_EditTargetButton);
    lv_obj_set_width(ui_MeasureButtonText6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureButtonText6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureButtonText6, 1);
    lv_obj_set_y(ui_MeasureButtonText6, -1);
    lv_obj_set_align(ui_MeasureButtonText6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureButtonText6, "Edit Target");
    lv_obj_set_style_text_color(ui_MeasureButtonText6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureButtonText6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MeasureButtonText6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentMeasurementLabel = lv_label_create(ui_MainControlScreen);
    lv_obj_set_width(ui_CurrentMeasurementLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentMeasurementLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentMeasurementLabel, -234);
    lv_obj_set_y(ui_CurrentMeasurementLabel, -170);
    lv_obj_set_align(ui_CurrentMeasurementLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentMeasurementLabel, "000.000");
    lv_obj_set_style_text_font(ui_CurrentMeasurementLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MAIN_CONTROL_SCREEN = ui_MainControlScreen;
    ui_MainControlsContainer = ui_MainControlsContainer;
    ui_MEASURE_BUTTON = ui_MeasureButton;
    ui_HOME_AXIS_BUTTON = ui_HomeAxisButton;
    ui_RESET_SERVO_BUTTON = ui_ResetServoButton;
    ui_SETTINGS_BUTTON = ui_SettingsButton;
    ui_EDIT_TARGET_BUTTON = ui_EditTargetButton;
    ui_CURRENT_MEASUREMENT_LABEL = ui_CurrentMeasurementLabel;

}

void ui_MainControlScreen_screen_destroy(void)
{
    if(ui_MainControlScreen) lv_obj_del(ui_MainControlScreen);

    // NULL screen variables
    ui_MAIN_CONTROL_SCREEN = NULL;
    ui_MainControlScreen = NULL;
    ui_MainControlsContainer = NULL;
    ui_MainControlsContainer = NULL;
    ui_MEASURE_BUTTON = NULL;
    ui_MeasureButton = NULL;
    ui_MeasureButtonText = NULL;
    ui_HOME_AXIS_BUTTON = NULL;
    ui_HomeAxisButton = NULL;
    ui_MeasureButtonText2 = NULL;
    ui_RESET_SERVO_BUTTON = NULL;
    ui_ResetServoButton = NULL;
    ui_MeasureButtonText3 = NULL;
    ui_SETTINGS_BUTTON = NULL;
    ui_SettingsButton = NULL;
    ui_MeasureButtonText1 = NULL;
    ui_EDIT_TARGET_BUTTON = NULL;
    ui_EditTargetButton = NULL;
    ui_MeasureButtonText6 = NULL;
    ui_CURRENT_MEASUREMENT_LABEL = NULL;
    ui_CurrentMeasurementLabel = NULL;

}
