// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Saw-Fence

#ifndef UI_PARAMETEREDITSCREEN_H
#define UI_PARAMETEREDITSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ParameterEditScreen
extern void ui_ParameterEditScreen_screen_init(void);
extern void ui_ParameterEditScreen_screen_destroy(void);
extern lv_obj_t * ui_ParameterEditScreen;
extern void ui_event_ParameterInputKeyboard(lv_event_t * e);
extern lv_obj_t * ui_ParameterInputKeyboard;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_ParameterInputTextArea;
// CUSTOM VARIABLES
extern lv_obj_t * ui_PARAMETER_EDIT_SCREEN;
extern lv_obj_t * ui_PARAMETER_INPUT_KEYBOARD;
extern lv_obj_t * ui_PARAMETER_INPUT_TEXT_AREA;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

