// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Saw-Fence

#include "../ui.h"

lv_obj_t * ui_PARAMETER_INPUT_TEXT_AREA;
lv_obj_t * ui_PARAMETER_INPUT_KEYBOARD;
lv_obj_t * ui_PARAMETER_EDIT_SCREEN;
lv_obj_t * ui_ParameterEditScreen;
lv_obj_t * ui_ParameterInputKeyboard;
lv_obj_t * ui_Container3;
lv_obj_t * ui_ParameterInputTextArea;

// event funtions
void ui_event_ParameterInputKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_keyboard_set_target(ui_ParameterInputKeyboard,  ui_ParameterInputTextArea);
    }
}

// build funtions

void ui_ParameterEditScreen_screen_init(void)
{
    ui_ParameterEditScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ParameterEditScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ParameterInputKeyboard = lv_keyboard_create(ui_ParameterEditScreen);
    lv_keyboard_set_mode(ui_ParameterInputKeyboard, LV_KEYBOARD_MODE_USER_4);
    lv_obj_set_width(ui_ParameterInputKeyboard, 539);
    lv_obj_set_height(ui_ParameterInputKeyboard, 400);
    lv_obj_set_x(ui_ParameterInputKeyboard, 14);
    lv_obj_set_y(ui_ParameterInputKeyboard, 40);
    lv_obj_set_align(ui_ParameterInputKeyboard, LV_ALIGN_CENTER);

    ui_Container3 = lv_obj_create(ui_ParameterEditScreen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 317);
    lv_obj_set_height(ui_Container3, 63);
    lv_obj_set_x(ui_Container3, 12);
    lv_obj_set_y(ui_Container3, -201);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ParameterInputTextArea = lv_textarea_create(ui_Container3);
    lv_obj_set_width(ui_ParameterInputTextArea, 244);
    lv_obj_set_height(ui_ParameterInputTextArea, 70);
    lv_obj_set_x(ui_ParameterInputTextArea, 12);
    lv_obj_set_y(ui_ParameterInputTextArea, 0);
    lv_obj_set_align(ui_ParameterInputTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ParameterInputTextArea, "0");
    lv_textarea_set_placeholder_text(ui_ParameterInputTextArea, "0");
    lv_obj_clear_flag(ui_ParameterInputTextArea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_ParameterInputTextArea, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_ParameterInputTextArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ParameterInputTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ParameterInputTextArea, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ParameterInputTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ParameterInputTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ParameterInputTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ParameterInputKeyboard, ui_event_ParameterInputKeyboard, LV_EVENT_ALL, NULL);
    ui_PARAMETER_EDIT_SCREEN = ui_ParameterEditScreen;
    ui_PARAMETER_INPUT_KEYBOARD = ui_ParameterInputKeyboard;
    ui_PARAMETER_INPUT_TEXT_AREA = ui_ParameterInputTextArea;

}

void ui_ParameterEditScreen_screen_destroy(void)
{
    if(ui_ParameterEditScreen) lv_obj_del(ui_ParameterEditScreen);

    // NULL screen variables
    ui_PARAMETER_EDIT_SCREEN = NULL;
    ui_ParameterEditScreen = NULL;
    ui_PARAMETER_INPUT_KEYBOARD = NULL;
    ui_ParameterInputKeyboard = NULL;
    ui_Container3 = NULL;
    ui_PARAMETER_INPUT_TEXT_AREA = NULL;
    ui_ParameterInputTextArea = NULL;

}
