// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Saw-Fence

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_UnitSwitch;
extern lv_obj_t * ui_EditHomeToBladeOffsetButton;
extern lv_obj_t * ui_MeasureButtonText5;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_ExitSettingsButton;
extern lv_obj_t * ui_MeasureButtonText8;
extern lv_obj_t * ui_EditHomeToBladeOffsetButton2;
extern lv_obj_t * ui_MeasureButtonText7;
// CUSTOM VARIABLES
extern lv_obj_t * ui_SETTINGS_SCREEN;
extern lv_obj_t * ui_UNIT_SWITCH;
extern lv_obj_t * ui_EDIT_HOME_TO_BLADE_OFFSET_BUTTON;
extern lv_obj_t * ui_EXIT_SETTINGS_BUTTON;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

