// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Saw-Fence

#ifndef UI_SPLASHSCREEN_H
#define UI_SPLASHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SplashScreen
extern void ui_SplashScreen_screen_init(void);
extern void ui_SplashScreen_screen_destroy(void);
extern lv_obj_t * ui_SplashScreen;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES
extern lv_obj_t * ui_SPLASH_SCREEN;
extern lv_obj_t * ui_Label1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

