// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Saw-Fence

#include "../ui.h"

lv_obj_t * ui_Label1;
lv_obj_t * ui_SPLASH_SCREEN;
lv_obj_t * ui_SplashScreen;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label1;

// event funtions

// build funtions

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_SplashScreen);
    lv_img_set_src(ui_Image3, &ui_img_988892695);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1034
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 614
    lv_obj_set_x(ui_Image3, -2);
    lv_obj_set_y(ui_Image3, -17);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 160);

    ui_Label1 = lv_label_create(ui_SplashScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 202);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Loading Application...");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPLASH_SCREEN = ui_SplashScreen;
    ui_Label1 = ui_Label1;

}

void ui_SplashScreen_screen_destroy(void)
{
    if(ui_SplashScreen) lv_obj_del(ui_SplashScreen);

    // NULL screen variables
    ui_SPLASH_SCREEN = NULL;
    ui_SplashScreen = NULL;
    ui_Image3 = NULL;
    ui_Label1 = NULL;
    ui_Label1 = NULL;

}
