// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: Saw-Fence

#include "../ui.h"

lv_obj_t * ui_EXIT_SETTINGS_BUTTON;
lv_obj_t * ui_EDIT_HOME_TO_BLADE_OFFSET_BUTTON;
lv_obj_t * ui_UNIT_SWITCH;
lv_obj_t * ui_SETTINGS_SCREEN;
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_UnitSwitch;
lv_obj_t * ui_EditHomeToBladeOffsetButton;
lv_obj_t * ui_MeasureButtonText5;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_ExitSettingsButton;
lv_obj_t * ui_MeasureButtonText8;
lv_obj_t * ui_EditHomeToBladeOffsetButton2;
lv_obj_t * ui_MeasureButtonText7;

// event funtions

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 215);
    lv_obj_set_height(ui_Container1, 100);
    lv_obj_set_x(ui_Container1, -279);
    lv_obj_set_y(ui_Container1, -58);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Container1, lv_color_hex(0x5AA5DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Container1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Container1, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -80);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "in");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 65);
    lv_obj_set_y(ui_Label4, -2);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "mm");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnitSwitch = lv_switch_create(ui_Container1);
    lv_obj_set_width(ui_UnitSwitch, 78);
    lv_obj_set_height(ui_UnitSwitch, 33);
    lv_obj_set_x(ui_UnitSwitch, -17);
    lv_obj_set_y(ui_UnitSwitch, 1);
    lv_obj_set_align(ui_UnitSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_UnitSwitch, lv_color_hex(0x32C156), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UnitSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EditHomeToBladeOffsetButton = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_EditHomeToBladeOffsetButton, 215);
    lv_obj_set_height(ui_EditHomeToBladeOffsetButton, 116);
    lv_obj_set_x(ui_EditHomeToBladeOffsetButton, -281);
    lv_obj_set_y(ui_EditHomeToBladeOffsetButton, 66);
    lv_obj_set_align(ui_EditHomeToBladeOffsetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EditHomeToBladeOffsetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EditHomeToBladeOffsetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeasureButtonText5 = lv_label_create(ui_EditHomeToBladeOffsetButton);
    lv_obj_set_width(ui_MeasureButtonText5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureButtonText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureButtonText5, 1);
    lv_obj_set_y(ui_MeasureButtonText5, -1);
    lv_obj_set_align(ui_MeasureButtonText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureButtonText5, "Edit Home to\n Blade Offset");
    lv_obj_set_style_text_color(ui_MeasureButtonText5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureButtonText5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MeasureButtonText5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 784);
    lv_obj_set_height(ui_Container2, 111);
    lv_obj_set_x(ui_Container2, 1);
    lv_obj_set_y(ui_Container2, -182);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Container2, lv_color_hex(0x5AA5DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Container2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, -2);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Settings");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExitSettingsButton = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_ExitSettingsButton, 231);
    lv_obj_set_height(ui_ExitSettingsButton, 84);
    lv_obj_set_x(ui_ExitSettingsButton, -273);
    lv_obj_set_y(ui_ExitSettingsButton, 183);
    lv_obj_set_align(ui_ExitSettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ExitSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ExitSettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeasureButtonText8 = lv_label_create(ui_ExitSettingsButton);
    lv_obj_set_width(ui_MeasureButtonText8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureButtonText8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureButtonText8, 1);
    lv_obj_set_y(ui_MeasureButtonText8, -1);
    lv_obj_set_align(ui_MeasureButtonText8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureButtonText8, "Exit");
    lv_obj_set_style_text_color(ui_MeasureButtonText8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureButtonText8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MeasureButtonText8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EditHomeToBladeOffsetButton2 = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_EditHomeToBladeOffsetButton2, 215);
    lv_obj_set_height(ui_EditHomeToBladeOffsetButton2, 116);
    lv_obj_set_x(ui_EditHomeToBladeOffsetButton2, 165);
    lv_obj_set_y(ui_EditHomeToBladeOffsetButton2, -25);
    lv_obj_set_align(ui_EditHomeToBladeOffsetButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EditHomeToBladeOffsetButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EditHomeToBladeOffsetButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MeasureButtonText7 = lv_label_create(ui_EditHomeToBladeOffsetButton2);
    lv_obj_set_width(ui_MeasureButtonText7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeasureButtonText7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MeasureButtonText7, 1);
    lv_obj_set_y(ui_MeasureButtonText7, -1);
    lv_obj_set_align(ui_MeasureButtonText7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeasureButtonText7, "Edit Home to\n Blade Offset");
    lv_obj_set_style_text_color(ui_MeasureButtonText7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MeasureButtonText7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MeasureButtonText7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SETTINGS_SCREEN = ui_SettingsScreen;
    ui_UNIT_SWITCH = ui_UnitSwitch;
    ui_EDIT_HOME_TO_BLADE_OFFSET_BUTTON = ui_EditHomeToBladeOffsetButton;
    ui_EXIT_SETTINGS_BUTTON = ui_ExitSettingsButton;

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SETTINGS_SCREEN = NULL;
    ui_SettingsScreen = NULL;
    ui_Container1 = NULL;
    ui_Label2 = NULL;
    ui_Label4 = NULL;
    ui_UNIT_SWITCH = NULL;
    ui_UnitSwitch = NULL;
    ui_EDIT_HOME_TO_BLADE_OFFSET_BUTTON = NULL;
    ui_EditHomeToBladeOffsetButton = NULL;
    ui_MeasureButtonText5 = NULL;
    ui_Container2 = NULL;
    ui_Label3 = NULL;
    ui_EXIT_SETTINGS_BUTTON = NULL;
    ui_ExitSettingsButton = NULL;
    ui_MeasureButtonText8 = NULL;
    ui_EditHomeToBladeOffsetButton2 = NULL;
    ui_MeasureButtonText7 = NULL;

}
